const POSTS_COUNT = 25;
const MIN_LIKES_COUNT = 15;
const MAX_LIKES_COUNT = 200;
const MIN_COUNT_COMMENTS = 0;
const MAX_COUNT_COMMENTS = 30;
const MIN_AVATARS_COUNT = 1;
const MAX_AVATARS_COUNT = 6;
const DESCRIPTIONS = [];
